"use client";
import { useEffect, useState, type ReactNode } from "react";
import { Wallet, ShieldCheck, CalendarDays, Upload, FolderOpen, ChevronLeft, ChevronRight } from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { toast } from "sonner";
import { balance, paid, money, today, localDate, calendarExport, type Booking, type Vault } from "@/lib/travel";
import { encrypt, download, type Keyring, type Envelope } from "@/lib/vault";
import { connectDrive, disconnectDrive, pushBackup, listBackups, pullBackup, type DriveBackup } from "@/lib/drive";
import { Choose, Field, Empty } from "./travel-forms";
export function CalendarView({bookings,onSelect,row}:{bookings:Booking[];onSelect:(id:string)=>void;row:(b:Booking)=>ReactNode}){
 const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[selected,setSelected]=useState("");
 const first=new Date(month.getFullYear(),month.getMonth(),1),start=new Date(first);start.setDate(1-first.getDay());const cells=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d;});
 const events=(date:string)=>bookings.filter(b=>b.start.slice(0,10)<=date&&b.end.slice(0,10)>=date),dues=(date:string)=>bookings.filter(b=>balance(b)>0&&b.due===date);
 return <><section className="panel"><div className="panelTitle"><h3>{month.toLocaleDateString("en-US",{month:"long",year:"numeric"})}</h3><div className="actions"><button className="secondary" aria-label="Previous month" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft size={18}/></button><button className="secondary" onClick={()=>{setMonth(new Date(new Date().getFullYear(),new Date().getMonth(),1));setSelected(today());}}>Today</button><button className="secondary" aria-label="Next month" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight size={18}/></button></div></div><small className="calendarNote">Reservations appear on their local travel dates. Amber marks payment deadlines.</small><div className="calendarGrid">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><div className="weekday" key={d}>{d}</div>)}{cells.map(d=>{const date=localDate(d),items=events(date),due=dues(date);return <button aria-label={date+", "+items.length+" reservations, "+due.length+" payments"} key={date} onClick={()=>setSelected(date)} className={"day "+(d.getMonth()!==month.getMonth()?"other ":"")+(date===today()?"today ":"")+(selected===date?"selected":"")}><span>{d.getDate()}</span>{items.slice(0,2).map(b=><small key={b.id} className="calEvent">{b.title}</small>)}{due.length>0&&<small className="calDue">{due.length} due</small>}{items.length>2&&<small>+{items.length-2}</small>}</button>})}</div></section>{selected&&<section className="panel"><div className="panelTitle"><h3>{selected}</h3><button className="secondary" onClick={()=>setSelected("")}>Clear day</button></div>{events(selected).map(row)}{dues(selected).map(b=><button key={b.id} className="paymentAlert" onClick={()=>onSelect(b.id)}>Payment due: {b.title} · {money(balance(b),b.currency)}</button>)}{!events(selected).length&&!dues(selected).length&&<Empty title="Nothing planned for this day"/>}</section>}</>;
}
export function PaymentView({bookings,onSelect,onPay}:{bookings:Booking[];onSelect:(id:string)=>void;onPay:(id:string)=>void}){
 const totals=Object.entries(bookings.filter(b=>balance(b)>0).reduce<Record<string,number>>((a,b)=>({...a,[b.currency]:(a[b.currency]||0)+balance(b)}),{}));
 return <><div className="balanceSummary"><Wallet/><div><h3>Remaining balances</h3><p>{totals.length?totals.map(([c,n])=>money(n,c)).join(" · "):"All recorded costs are paid"}</p><small>Currencies are kept separate. No estimated exchange rates.</small></div></div><section className="panel">{bookings.filter(b=>b.total>0).length?bookings.filter(b=>b.total>0).map(b=><div className="paymentCard" key={b.id}><div className="panelTitle"><button className="textButton" onClick={()=>onSelect(b.id)}>{b.title}</button><span className={"pill "+(balance(b)?"warn":"good")}>{balance(b)?b.due?(b.due<today()?"Overdue ":"Due ")+b.due:"Deadline not set":"Paid in full"}</span></div><div className="paymentNumbers"><span><small>Total cost</small>{money(b.total,b.currency)}</span><span><small>Paid</small>{money(paid(b),b.currency)}</span><span><small>Remaining</small><b>{money(balance(b),b.currency)}</b></span></div><Progress value={b.total?paid(b)/b.total*100:0} aria-label="Payment progress"/><div className="paymentHistory">{b.payments.map(p=><div key={p.id}><span>{p.date} · {p.note||"Payment recorded"}</span><strong>{money(p.amount,b.currency)}</strong></div>)}</div>{balance(b)>0&&<button className="secondary" onClick={()=>onPay(b.id)}>Record payment</button>}</div>):<Empty title="No reservation costs yet"><p>Add a total cost and due date to any reservation.</p></Empty>}</section></>;
}
export function SettingsView({vault,ring,stored,disabled,run,onUnlock,onFileRestore,onRestore}:{vault:Vault;ring:Keyring|null;stored:boolean;disabled:boolean;run:(f:()=>Promise<void>)=>Promise<void>;onUnlock:()=>void;onFileRestore:()=>void;onRestore:(e:Envelope)=>void}){
 const [clientId,setClientId]=useState(""),[connected,setConnected]=useState(false),[backups,setBackups]=useState<DriveBackup[]>([]),[restoreId,setRestoreId]=useState("");
 useEffect(()=>setClientId(localStorage.getItem("travel-google-client")||""),[]);
 return <div className="settingsGrid"><section className="panel"><ShieldCheck className="sectionIcon"/><h3>Your encrypted travel vault</h3><p>Reservations and attachments are encrypted with your passphrase. Keep that passphrase safe: there is no password reset.</p>{!ring?<button className="primary" disabled={disabled} onClick={onUnlock}>{stored?"Unlock vault":"Create vault"}</button>:<><p className="notice">Saved on this device. Keep a backup to protect against browser storage being cleared.</p><button className="primary" onClick={()=>run(async()=>{const e=await encrypt(vault,ring);download(JSON.stringify(e),"my-travel-bot-"+today()+".travel");toast.success("Encrypted backup downloaded.");})}>Download encrypted backup</button></>}<button className="secondary restoreButton" disabled={disabled} onClick={onFileRestore}>Restore encrypted backup</button><small>Restoring replaces this device's vault after confirmation. Download a backup first if it contains changes you want to keep.</small></section>

 <section className="panel"><FolderOpen className="sectionIcon"/><h3>Google Drive app storage</h3><p>Keep encrypted snapshots in your Google account and restore them on your phone. Only this app can access its hidden app folder.</p><Field label="Google OAuth web client ID"><input placeholder="…apps.googleusercontent.com" value={clientId} onChange={e=>{setClientId(e.target.value);localStorage.setItem("travel-google-client",e.target.value);}}/></Field><div className="actions"><button className="primary" onClick={()=>run(async()=>{await connectDrive(clientId.trim());setConnected(true);setBackups(await listBackups());toast.success("Google Drive connected.");})}>{connected?"Reconnect Google Drive":"Connect Google Drive"}</button>{connected&&<button className="secondary" onClick={()=>{disconnectDrive();setConnected(false);setBackups([]);}}>Disconnect</button>}</div>{connected&&<><div className="actions"><button className="secondary" disabled={!ring} onClick={()=>run(async()=>{if(!ring)return;await pushBackup(await encrypt(vault,ring));setBackups(await listBackups());toast.success("Encrypted snapshot saved to Google Drive.");})}>Back up now</button><button className="secondary" onClick={()=>run(async()=>setBackups(await listBackups()))}>Refresh backups</button></div>{backups.length>0?<><Choose label="Choose Drive backup" value={restoreId} onChange={setRestoreId} options={backups.map(b=>({value:b.id,label:new Date(b.modifiedTime).toLocaleString()}))}/><button className="secondary" disabled={!restoreId} onClick={()=>run(async()=>onRestore(await pullBackup(restoreId)))}>Restore selected snapshot</button></>:<small>No snapshots yet. Back up from the device with your current trip details.</small>}</>}<details><summary>One-time Google setup</summary><ol><li>Enable the Google Drive API in your Google Cloud project.</li><li>Create an OAuth client of type Web application.</li><li>Add this app's origin to Authorized JavaScript origins: <code>{typeof window!=="undefined"?window.location.origin:"your deployed app URL"}</code>.</li><li>Configure the consent screen and add your account as a test user if needed. Paste the client ID above.</li></ol><a target="_blank" rel="noreferrer" href="https://developers.google.com/workspace/drive/api/guides/appdata">Google's app storage documentation ↗</a></details><small>Backups are manual snapshots, not live sync. Restore the newest snapshot before editing on another device. Google account storage limits apply.</small></section>
 <section className="panel"><CalendarDays className="sectionIcon"/><h3>Take it on your phone</h3><p>Open the deployed app on your phone, add it to your home screen, and restore your encrypted backup using the same passphrase.</p><p>After the app loads online, its installed shell and saved vault can open offline. Test offline access before departure. Download attachments you may need outside the app.</p><p>Export calendar reminders and import the file into Apple Calendar, Google Calendar, or Outlook. Re-export after dates or balances change. Your calendar app controls alert delivery.</p>{ring&&<button className="secondary" onClick={()=>download(calendarExport(vault.bookings),"my-travel-calendar.ics","text/calendar")}>Export all calendar reminders</button>}</section>
 <section className="panel"><Upload className="sectionIcon"/><h3>Flexible imports</h3><p>Import CSV and calendar files with a review step. Paste confirmation text or attach any file and enter the essential dates. Original documents stay attached to the reservation.</p><p>Scanned PDFs and photos are stored as originals; this version does not guess dates using OCR or AI.</p><button className="secondary" onClick={()=>download('kind,title,start,end,zone,endZone,location,confirmation,total,currency,due,notes\r\nHotel,Example hotel,2026-10-10T15:00,2026-10-12T11:00,Europe/Rome,Europe/Rome,Rome,EXAMPLE,400,EUR,2026-10-01,Check-in details\r\n',"travel-import-template.csv","text/csv")}>Download CSV template</button></section></div>;
}
