"use client";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { Plane, CalendarDays, Wallet, FolderOpen, Settings, Plus, ShieldCheck, Upload, Download, MapPin, Search, ArrowUpRight } from "lucide-react";
import { SidebarProvider, Sidebar, SidebarContent, SidebarHeader, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger } from "@/components/ui/sidebar";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from "@/components/ui/alert-dialog";
import { Toaster, toast } from "sonner";
import { bookingLocation, balance, paid, money, uid, today, stamp, instant, emptyVault, blankBooking, vaultSchema, calendarExport, type Booking, type Vault } from "@/lib/travel";
import { derive, encrypt, decrypt, readVault, writeVault, download, fileData, downloadArtifact, parseEnvelope, type Envelope, type Keyring } from "@/lib/vault";
import { registerTravelTools } from "@/lib/webmcp";
import { disconnectDrive } from "@/lib/drive";
import { Choose, Field, Empty, BookingForm, ReservationDetail, ImportForm } from "./travel-forms";
import { CalendarView, PaymentView, SettingsView } from "./travel-views";
const views=[{name:"Overview",icon:Plane},{name:"Calendar",icon:CalendarDays},{name:"Payments",icon:Wallet},{name:"Documents",icon:FolderOpen},{name:"Settings",icon:Settings}] as const;
export default function TravelApp(){
 const [view,setView]=useState("Overview"),[vault,setVault]=useState<Vault>(emptyVault),[ring,setRing]=useState<Keyring|null>(null),[stored,setStored]=useState<Envelope>(),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[saveStatus,setSaveStatus]=useState(""),[loadError,setLoadError]=useState("");
 const [trip,setTrip]=useState("all"),[search,setSearch]=useState(""),[modal,setModal]=useState(""),[password,setPassword]=useState(""),[confirmPass,setConfirmPass]=useState(""),[draft,setDraft]=useState<Booking|null>(null),[detail,setDetail]=useState(""),[pendingRestore,setPendingRestore]=useState<Envelope>(),[pendingDelete,setPendingDelete]=useState<{title:string;next:Vault}|null>(null),[offline,setOffline]=useState(false);
 const busyRef=useRef(false),attachRef=useRef<HTMLInputElement>(null),restoreRef=useRef<HTMLInputElement>(null);const [attachmentTarget,setAttachmentTarget]=useState("");
 const liveVault=useRef<Vault|null>(null);liveVault.current=ring?vault:null;
 useEffect(()=>registerTravelTools(()=>liveVault.current),[]);
 const active=vault.bookings.find(b=>b.id===detail);
 useEffect(()=>{readVault().then(e=>setStored(e)).catch(()=>setLoadError("Your saved vault could not be read. Reload before creating or restoring a vault.")).finally(()=>setLoaded(true));const update=()=>setOffline(!navigator.onLine);update();window.addEventListener("online",update);window.addEventListener("offline",update);if("serviceWorker" in navigator&&process.env.NODE_ENV==="production")navigator.serviceWorker.register("/sw.js").catch(()=>toast.error("Offline installation is unavailable in this browser."));return()=>{window.removeEventListener("online",update);window.removeEventListener("offline",update);};},[]);
 async function run(action:()=>Promise<void>){if(busyRef.current)return;busyRef.current=true;setBusy(true);try{await action();}catch(e){toast.error(e instanceof Error?e.message:String(e),{duration:7000});}finally{busyRef.current=false;setBusy(false);}}
 async function commit(next:Vault){if(!ring)throw new Error("Unlock your vault first.");const valid=vaultSchema.parse(next);setSaveStatus("Saving…");try{const e=await encrypt(valid,ring);await writeVault(e,stored?.updated??null);setVault(valid);setStored(e);setSaveStatus("Saved on this device");}catch(e){setSaveStatus("Save failed — please retry");throw e;}}
 function needVault(action:()=>void){if(!ring){setModal("vault");return;}action();}
 function newBooking(){needVault(()=>{if(!vault.trips.length){setModal("trip");return;}setDraft(blankBooking(trip==="all"?vault.trips[0].id:trip));setDetail("");setModal("booking");});}
 function startImport(){needVault(()=>{setModal(vault.trips.length?"import":"trip");});}
 const filtered=vault.bookings.filter(b=>(trip==="all"||b.tripId===trip)&&[b.title,b.location,b.fromAirport,b.toAirport,b.airline,b.flightNumber,b.confirmation,b.notes,b.kind].join(" ").toLowerCase().includes(search.toLowerCase())).sort((a,b)=>instant(a.start,a.zone)-instant(b.start,b.zone));
 const outstanding=filtered.filter(b=>balance(b)>0).sort((a,b)=>(a.due||"9999").localeCompare(b.due||"9999"));
 const attachments=vault.artifacts.filter(a=>(trip==="all"||a.tripId===trip)&&a.name.toLowerCase().includes(search.toLowerCase()));
 const getTrip=(id:string)=>vault.trips.find(t=>t.id===id)?.name||"";
 function chooseAttachment(bookingId=""){if(!vault.trips.length){setModal("trip");return;}setAttachmentTarget(bookingId);attachRef.current?.click();}
 function reservationRow(b:Booking){return <button key={b.id} className="reservationRow" onClick={()=>setDetail(b.id)}><span className={"glyph "+b.kind.split(" ")[0].toLowerCase()}>{b.kind==="Flight"?<Plane size={21}/>:<MapPin size={21}/>}</span><span className="reservationName"><strong>{b.title}</strong><small>{bookingLocation(b)||getTrip(b.tripId)} · {b.kind}</small></span><span className="reservationDate"><strong>{stamp(b)}</strong><small>{b.zone.replace(/_/g," ")}</small></span><span className={"pill "+(balance(b)>0?"warn":"good")}>{b.total===0?"No cost entered":balance(b)>0?money(balance(b),b.currency)+" left":"Paid"}</span><ArrowUpRight size={17}/></button>}
 function confirmDelete(title:string,next:Vault){setPendingDelete({title,next});}
 const restore=(e:Envelope)=>{setPendingRestore(e);setPassword("");setModal("restore");};
 return <SidebarProvider><Toaster richColors position="top-center"/><Sidebar><SidebarHeader><div className="brand"><span className="brandMark"><Plane/></span><div><strong>My Travel Bot</strong><small>YOUR TRAVEL COMPANION</small></div></div></SidebarHeader><SidebarContent><SidebarMenu>{views.map(({name,icon:Icon})=><SidebarMenuItem key={name}><SidebarMenuButton isActive={view===name} onClick={()=>setView(name)}><Icon/><span>{name}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sideNote"><ShieldCheck/><strong>{ring?"Your travel vault is open":"Your plans. Kept private."}</strong><p>{ring?"Export calendar reminders before you travel.":"Encrypted reservations and documents, ready to take with you."}</p>{ring&&<button className="secondary" disabled={busy} onClick={()=>{setRing(null);setVault(emptyVault());setDetail("");setDraft(null);setPendingDelete(null);setPendingRestore(undefined);setSearch("");setModal("");disconnectDrive();setSaveStatus("");}}>Lock vault</button>}</div><small role="status">{offline?"Offline · this device only":saveStatus||"Encrypted storage"}</small></SidebarContent></Sidebar>
 <main><fieldset disabled={busy} className="appFieldset"><header className="topbar"><div><SidebarTrigger className="mobileMenu"/><p className="eyebrow">MY TRAVEL BOT / {view}</p><h1>{view==="Overview"?"Everything for your next escape.":view==="Calendar"?"Make room for the memories.":view==="Payments"?"Every payment, accounted for.":view==="Documents"?"The details, right at hand.":"Ready to travel with you."}</h1></div><div className="actions"><button className="secondary" onClick={startImport}><Upload size={17}/> Import</button><button className="primary" onClick={()=>needVault(()=>setModal("trip"))}><Plus size={18}/> New trip</button></div></header>
 {busy&&<div className="notice" role="status">Saving or transferring your encrypted information…</div>}{loadError&&<div className="notice error" role="alert">{loadError}</div>}

 {!ring&&view!=="Settings"?<><section className="welcome panel"><div><p className="eyebrow">A LITTLE PLANNING. A LOT OF PEACE OF MIND.</p><h2>Your whole trip.<br/>One place.</h2><p>Flights, stays, drives, and the moments in between.<br/>Keep the details close, wherever you go.</p><div className="actions"><button className="primary" disabled={!loaded||!!loadError} onClick={()=>setModal("vault")}>{!loaded?"Opening…":stored?"Unlock your travel vault":"Create your travel vault"}</button><button className="secondary" onClick={()=>setView("Settings")}>Restore a backup</button></div></div><div className="ticket"><Plane size={28}/><span>YOUR NEXT ADVENTURE</span><strong>Let's get you<br/>going.</strong><div><MapPin size={17}/> Wherever you want to be</div></div></section><div className="metricGrid">{["Flights & reservations","Payment deadlines","Travel documents","Offline access"].map((t,i)=><section className="metric" key={t}><span>{String(i+1).padStart(2,"0")}</span><h3>{t}</h3><small>{["All the details together","Know what's paid and due","Attach tickets and confirmations","Carry your encrypted vault"][i]}</small></section>)}</div></>:
 <>{view!=="Settings"&&<div className="toolbar"><Choose label="Filter by trip" value={trip} onChange={setTrip} options={[{value:"all",label:"All trips"},...vault.trips.map(t=>({value:t.id,label:t.name}))]}/><label className="search"><Search size={17}/><input aria-label="Search reservations or documents" placeholder="Search your travel details…" value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="secondary" onClick={()=>download(calendarExport(filtered),"my-travel-calendar.ics","text/calendar")}><Download size={16}/> Calendar reminders</button></div>}
 {view==="Overview"&&<><div className="metricGrid">{[["Upcoming reservations",filtered.filter(b=>instant(b.end,b.endZone)>=Date.now()).length,"Flights, stays & experiences"],["Payments to make",outstanding.length,outstanding.filter(b=>b.due&&b.due<today()).length+" overdue"],["Travel documents",attachments.length,"Available in your vault"],["Trips organized",vault.trips.length,"Every journey in one place"]].map(([title,n,note])=><section className="metric" key={title}><span>{title}</span><strong>{n}</strong><small>{note}</small></section>)}</div>
 <div className="twoCol"><section className="panel"><div className="panelTitle"><div><p className="eyebrow">YOUR JOURNEY</p><h3>Trips & destinations</h3></div><button className="textButton" onClick={()=>setModal("trip")}>+ Add trip</button></div>{vault.trips.length?vault.trips.filter(t=>trip==="all"||t.id===trip).map(t=><div className="tripCard" key={t.id}><button onClick={()=>setTrip(t.id)}><MapPin size={21}/><span><strong>{t.name}</strong><small>{t.destination||"Destination to be decided"} · {vault.bookings.filter(b=>b.tripId===t.id).length} reservations</small></span></button>{t.notes&&<p>{t.notes}</p>}<button className="textButton dangerText" onClick={()=>confirmDelete("trip and all its reservations, payments, and documents",{...vault,trips:vault.trips.filter(x=>x.id!==t.id),bookings:vault.bookings.filter(b=>b.tripId!==t.id),artifacts:vault.artifacts.filter(a=>a.tripId!==t.id)})}>Delete trip</button></div>):<Empty title="Your next adventure starts here"><p>Add a trip, then bring in your reservations.</p><button className="primary" onClick={()=>setModal("trip")}>Create first trip</button></Empty>}</section><section className="panel"><div className="panelTitle"><div><p className="eyebrow">AHEAD OF THE DETAILS</p><h3>Needs your attention</h3></div><Wallet size={21}/></div>{outstanding.length?outstanding.slice(0,3).map(b=><button className="attention" key={b.id} onClick={()=>setDetail(b.id)}><span><strong>{b.title}</strong><small className={b.due&&b.due<today()?"dangerText":""}>{b.due?"Due "+b.due:"Set a payment deadline"}</small></span><b>{money(balance(b),b.currency)}</b></button>):<Empty title="No outstanding payments"><p>Payment deadlines will appear here.</p></Empty>}<small>For reminders while the app is closed, add the calendar export to your phone's calendar.</small></section></div>
 <section className="panel"><div className="panelTitle"><div><p className="eyebrow">ALL THE MOMENTS IN BETWEEN</p><h3>Your itinerary</h3></div><button className="primary" onClick={newBooking}><Plus size={16}/> Add reservation</button></div>{filtered.length?filtered.map(reservationRow):<Empty title="A fresh page in your travel journal"><p>Add a flight, hotel, rental car, or excursion.</p></Empty>}</section></>}
 {view==="Calendar"&&<CalendarView bookings={filtered} onSelect={setDetail} row={reservationRow}/>}
 {view==="Payments"&&<PaymentView bookings={filtered} onSelect={setDetail} onPay={id=>{setDetail(id);setModal("payment");}}/>}
 {view==="Documents"&&<section className="panel"><div className="panelTitle"><div><h3>Your travel documents</h3><small>{trip==="all"?"Choose a trip before attaching trip-level documents.":"Attachments stay linked to this trip or a reservation."}</small></div><button disabled={trip==="all"} className="primary" onClick={()=>chooseAttachment()}>Attach files</button></div><div className="documentGrid">{attachments.map(a=><div className="documentCard" key={a.id}><FolderOpen/><strong>{a.name}</strong><small>{vault.bookings.find(b=>b.id===a.bookingId)?.title||getTrip(a.tripId)}</small><small>{(a.size/1024).toFixed(0)} KB · Added {a.added}</small><div className="actions"><button className="secondary" onClick={()=>downloadArtifact(a.data,a.name)}>Download</button><button className="textButton dangerText" onClick={()=>confirmDelete("document",{...vault,artifacts:vault.artifacts.filter(x=>x.id!==a.id)})}>Remove</button></div></div>)}</div>{!attachments.length&&<Empty title="A place for every important detail"><p>Attach boarding passes, confirmations, receipts, photos, and other files to a trip or reservation.</p></Empty>}</section>}
 {view==="Settings"&&<SettingsView vault={vault} ring={ring} stored={!!stored} disabled={!loaded||!!loadError} run={run} onUnlock={()=>setModal("vault")} onFileRestore={()=>restoreRef.current?.click()} onRestore={restore}/>}
 </>}</fieldset>
 <input hidden type="file" multiple ref={attachRef} onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value="";void run(async()=>{if(vault.artifacts.reduce((n,a)=>n+a.size,0)+files.reduce((n,f)=>n+f.size,0)>50*1024*1024)throw new Error("This vault is limited to 50 MB of attachments.");const b=vault.bookings.find(x=>x.id===attachmentTarget),tripId=b?.tripId||(trip==="all"?vault.trips[0]?.id:trip);const added=await Promise.all(files.map(async f=>({id:uid(),tripId,bookingId:attachmentTarget,name:f.name,type:f.type,data:await fileData(f),size:f.size,added:today()})));await commit({...vault,artifacts:[...vault.artifacts,...added]});toast.success("Documents attached and encrypted.");});}}/>
 <input hidden type="file" accept=".travel,.json" ref={restoreRef} onChange={e=>{const f=e.target.files?.[0];e.target.value="";if(f)void run(async()=>{if(f.size>100_000_000)throw new Error("Backup is too large.");restore(parseEnvelope(JSON.parse(await f.text())));});}}/>
 </main>

 <Dialog open={modal==="vault"||modal==="restore"} onOpenChange={o=>{if(!o&&!busy){setModal("");setPassword("");setConfirmPass("");}}}><DialogContent><DialogTitle>{modal==="restore"?"Restore encrypted backup":stored?"Unlock your travel vault":"Create your travel vault"}</DialogTitle><DialogDescription>{modal==="restore"?"This replaces the vault on this device. Use the backup's passphrase. Download a backup first to preserve current changes.":stored?"Enter your passphrase to open your reservations and documents.":"Choose at least 12 characters. You will need this passphrase on every device. It cannot be recovered."}</DialogDescription><form className="stack" onSubmit={e=>{e.preventDefault();void run(async()=>{if(modal==="restore"){if(!pendingRestore)throw new Error("Choose a backup first.");const result=await decrypt(pendingRestore,password);await writeVault(pendingRestore);setStored(pendingRestore);setVault(result.vault);setRing(result.ring);setPendingRestore(undefined);setTrip("all");setDetail("");}else if(stored){const result=await decrypt(stored,password);setVault(result.vault);setRing(result.ring);}else{if(password!==confirmPass)throw new Error("Passphrases do not match.");const key=await derive(password),v=emptyVault(),encrypted=await encrypt(v,key);await writeVault(encrypted,null);setStored(encrypted);setVault(v);setRing(key);void navigator.storage?.persist?.();}setPassword("");setConfirmPass("");setModal("");setSaveStatus("Saved on this device");toast.success("Vault is ready.");});}}><Field label="Vault passphrase"><input autoFocus type="password" minLength={12} required autoComplete={stored?"current-password":"new-password"} value={password} onChange={e=>setPassword(e.target.value)}/></Field>{!stored&&modal!=="restore"&&<Field label="Confirm passphrase"><input type="password" required minLength={12} autoComplete="new-password" value={confirmPass} onChange={e=>setConfirmPass(e.target.value)}/></Field>}<button className="primary" disabled={busy||!!loadError}>{busy?"Opening securely…":modal==="restore"?"Replace this device's vault":stored?"Unlock vault":"Create vault"}</button></form></DialogContent></Dialog>
 <Dialog open={modal==="trip"} onOpenChange={o=>!o&&!busy&&setModal("")}><DialogContent><DialogTitle>A new adventure</DialogTitle><DialogDescription>Give your trip a name, then add its reservations.</DialogDescription><form className="stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{const id=uid();await commit({...vault,trips:[...vault.trips,{id,name:String(f.get("name")).trim(),destination:String(f.get("destination")),notes:String(f.get("notes"))}]});setTrip(id);setModal("");toast.success("Trip created.");});}}><Field label="Trip name"><input name="name" required placeholder="Autumn in Italy" autoFocus/></Field><Field label="Destination"><input name="destination" placeholder="Rome & the Amalfi Coast"/></Field><Field label="Trip notes"><textarea name="notes" placeholder="Travelers, emergency contacts, or anything to remember"/></Field><button className="primary" disabled={busy}>Create trip</button></form></DialogContent></Dialog>
 <Dialog open={modal==="booking"} onOpenChange={o=>!o&&!busy&&setModal("")}><DialogContent className="wideDialog"><DialogTitle>{vault.bookings.some(b=>b.id===draft?.id)?"Edit reservation":"Add reservation"}</DialogTitle><DialogDescription>Use the local date, time, and time zone at each location.</DialogDescription>{draft&&<BookingForm initial={draft} trips={vault.trips} busy={busy} onSave={b=>run(async()=>{await commit({...vault,bookings:[...vault.bookings.filter(x=>x.id!==b.id),b],artifacts:vault.artifacts.map(a=>a.bookingId===b.id?{...a,tripId:b.tripId}:a)});setModal("");setDetail(b.id);toast.success("Reservation saved.");})}/>}</DialogContent></Dialog>
 <Dialog open={!!active&&!modal} onOpenChange={o=>!o&&!busy&&setDetail("")}><DialogContent className="wideDialog"><DialogTitle>{active?.title}</DialogTitle><DialogDescription>{active?.kind} · {active&&getTrip(active.tripId)}</DialogDescription>{active&&<ReservationDetail booking={active} vault={vault} busy={busy} onAttach={()=>chooseAttachment(active.id)} onPay={()=>setModal("payment")} onEdit={()=>{setDraft(active);setModal("booking");}} onDelete={confirmDelete}/>}</DialogContent></Dialog>
 <Dialog open={modal==="payment"} onOpenChange={o=>!o&&!busy&&setModal("")}><DialogContent><DialogTitle>Record payment</DialogTitle><DialogDescription>{active?.title} · {active&&money(balance(active),active.currency)} remaining. This logs a payment you already made; it does not charge a card.</DialogDescription><form className="stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{if(!active)throw new Error("Choose a reservation.");const payment={id:uid(),amount:Number(f.get("amount")),date:String(f.get("date")),note:String(f.get("note"))};await commit({...vault,bookings:vault.bookings.map(b=>b.id===active.id?{...b,payments:[...b.payments,payment]}:b)});setModal("");toast.success("Payment recorded.");});}}><Field label={"Amount ("+(active?.currency||"")+")"}><input name="amount" type="number" min=".01" step=".01" max={active?balance(active):0} required autoFocus/></Field><Field label="Date paid"><input name="date" type="date" required max={today()} defaultValue={today()}/></Field><Field label="Reference / method"><input name="note" placeholder="Deposit · Visa ending 1234"/></Field><button className="primary" disabled={busy}>Save payment</button></form></DialogContent></Dialog>
 <Dialog open={modal==="import"} onOpenChange={o=>!o&&!busy&&setModal("")}><DialogContent className="wideDialog"><DialogTitle>Bring your travel details together</DialogTitle><DialogDescription>Review dates before saving. Text and arbitrary files become a draft you complete; CSV and ICS create structured previews.</DialogDescription><ImportForm vault={vault} trip={trip} busy={busy} run={run} onSave={async next=>{await commit(next);setModal("");toast.success("Reservations and originals imported.");}}/></DialogContent></Dialog>
 <AlertDialog open={!!pendingDelete} onOpenChange={o=>!o&&!busy&&setPendingDelete(null)}><AlertDialogContent><AlertDialogTitle>Delete this {pendingDelete?.title}?</AlertDialogTitle><AlertDialogDescription>This removes the selected records from this device's vault. Existing backup snapshots are unchanged.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void run(async()=>{if(!pendingDelete)return;await commit(pendingDelete.next);if(!pendingDelete.next.trips.some(t=>t.id===trip))setTrip("all");setPendingDelete(null);toast.success("Deleted.");});}}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </SidebarProvider>;
}
